[package]
name = "ater"
description = "Another text editor in rust"
version = "0.0.1"
edition = "2021"
authors = ["Ismael Aderdor Domingo <info@iaderdor.info>"]

[dependencies]
anyhow = "1.0.89"
crossterm = "0.28.1"
